<?php
/**
 * ResponseItem
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Dhl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Parcel DE Shipping API (Post & Parcel Germany)
 *
 * Note: This is the specification of the DPDHL Group Parcel DE Shipping API for Post & Parcel Germany. This REST web service allows business customers to create shipping labels on demand.
 *
 * The version of the OpenAPI document: 2.1.12
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Dhl\Model;

use \ArrayAccess;
use \OpenAPI\Client\Dhl\ObjectSerializer;

/**
 * ResponseItem Class Doc Comment
 *
 * @category Class
 * @description Response for a single shipment containing status, numbers and labels
 * @package  OpenAPI\Client\Dhl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ResponseItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ResponseItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'shipmentNo' => 'string',
        'routingCode' => 'string',
        'returnShipmentNo' => 'string',
        'sstatus' => '\OpenAPI\Client\Dhl\Model\RequestStatus',
        'shipmentRefNo' => 'string',
        'label' => '\OpenAPI\Client\Dhl\Model\Document',
        'returnLabel' => '\OpenAPI\Client\Dhl\Model\Document',
        'customsDoc' => '\OpenAPI\Client\Dhl\Model\Document',
        'codLabel' => '\OpenAPI\Client\Dhl\Model\Document',
        'validationMessages' => '\OpenAPI\Client\Dhl\Model\ValidationMessageItem[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'shipmentNo' => null,
        'routingCode' => null,
        'returnShipmentNo' => null,
        'sstatus' => null,
        'shipmentRefNo' => null,
        'label' => null,
        'returnLabel' => null,
        'customsDoc' => null,
        'codLabel' => null,
        'validationMessages' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'shipmentNo' => false,
        'routingCode' => false,
        'returnShipmentNo' => false,
        'sstatus' => false,
        'shipmentRefNo' => false,
        'label' => false,
        'returnLabel' => false,
        'customsDoc' => false,
        'codLabel' => false,
        'validationMessages' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'shipmentNo' => 'shipmentNo',
        'routingCode' => 'routingCode',
        'returnShipmentNo' => 'returnShipmentNo',
        'sstatus' => 'sstatus',
        'shipmentRefNo' => 'shipmentRefNo',
        'label' => 'label',
        'returnLabel' => 'returnLabel',
        'customsDoc' => 'customsDoc',
        'codLabel' => 'codLabel',
        'validationMessages' => 'validationMessages'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'shipmentNo' => 'setShipmentNo',
        'routingCode' => 'setRoutingCode',
        'returnShipmentNo' => 'setReturnShipmentNo',
        'sstatus' => 'setSstatus',
        'shipmentRefNo' => 'setShipmentRefNo',
        'label' => 'setLabel',
        'returnLabel' => 'setReturnLabel',
        'customsDoc' => 'setCustomsDoc',
        'codLabel' => 'setCodLabel',
        'validationMessages' => 'setValidationMessages'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'shipmentNo' => 'getShipmentNo',
        'routingCode' => 'getRoutingCode',
        'returnShipmentNo' => 'getReturnShipmentNo',
        'sstatus' => 'getSstatus',
        'shipmentRefNo' => 'getShipmentRefNo',
        'label' => 'getLabel',
        'returnLabel' => 'getReturnLabel',
        'customsDoc' => 'getCustomsDoc',
        'codLabel' => 'getCodLabel',
        'validationMessages' => 'getValidationMessages'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('shipmentNo', $data ?? [], null);
        $this->setIfExists('routingCode', $data ?? [], null);
        $this->setIfExists('returnShipmentNo', $data ?? [], null);
        $this->setIfExists('sstatus', $data ?? [], null);
        $this->setIfExists('shipmentRefNo', $data ?? [], null);
        $this->setIfExists('label', $data ?? [], null);
        $this->setIfExists('returnLabel', $data ?? [], null);
        $this->setIfExists('customsDoc', $data ?? [], null);
        $this->setIfExists('codLabel', $data ?? [], null);
        $this->setIfExists('validationMessages', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['shipmentNo']) && (mb_strlen($this->container['shipmentNo']) > 50)) {
            $invalidProperties[] = "invalid value for 'shipmentNo', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['shipmentNo']) && (mb_strlen($this->container['shipmentNo']) < 0)) {
            $invalidProperties[] = "invalid value for 'shipmentNo', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['routingCode']) && (mb_strlen($this->container['routingCode']) > 35)) {
            $invalidProperties[] = "invalid value for 'routingCode', the character length must be smaller than or equal to 35.";
        }

        if (!is_null($this->container['routingCode']) && (mb_strlen($this->container['routingCode']) < 0)) {
            $invalidProperties[] = "invalid value for 'routingCode', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['returnShipmentNo']) && (mb_strlen($this->container['returnShipmentNo']) > 50)) {
            $invalidProperties[] = "invalid value for 'returnShipmentNo', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['returnShipmentNo']) && (mb_strlen($this->container['returnShipmentNo']) < 0)) {
            $invalidProperties[] = "invalid value for 'returnShipmentNo', the character length must be bigger than or equal to 0.";
        }

        if ($this->container['sstatus'] === null) {
            $invalidProperties[] = "'sstatus' can't be null";
        }
        if (!is_null($this->container['shipmentRefNo']) && (mb_strlen($this->container['shipmentRefNo']) > 50)) {
            $invalidProperties[] = "invalid value for 'shipmentRefNo', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['shipmentRefNo']) && (mb_strlen($this->container['shipmentRefNo']) < 6)) {
            $invalidProperties[] = "invalid value for 'shipmentRefNo', the character length must be bigger than or equal to 6.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets shipmentNo
     *
     * @return string|null
     */
    public function getShipmentNo()
    {
        return $this->container['shipmentNo'];
    }

    /**
     * Sets shipmentNo
     *
     * @param string|null $shipmentNo shipmentNo
     *
     * @return self
     */
    public function setShipmentNo($shipmentNo)
    {
        if (is_null($shipmentNo)) {
            throw new \InvalidArgumentException('non-nullable shipmentNo cannot be null');
        }
        if ((mb_strlen($shipmentNo) > 50)) {
            throw new \InvalidArgumentException('invalid length for $shipmentNo when calling ResponseItem., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($shipmentNo) < 0)) {
            throw new \InvalidArgumentException('invalid length for $shipmentNo when calling ResponseItem., must be bigger than or equal to 0.');
        }

        $this->container['shipmentNo'] = $shipmentNo;

        return $this;
    }

    /**
     * Gets routingCode
     *
     * @return string|null
     */
    public function getRoutingCode()
    {
        return $this->container['routingCode'];
    }

    /**
     * Sets routingCode
     *
     * @param string|null $routingCode Routing code of the consignee address
     *
     * @return self
     */
    public function setRoutingCode($routingCode)
    {
        if (is_null($routingCode)) {
            throw new \InvalidArgumentException('non-nullable routingCode cannot be null');
        }
        if ((mb_strlen($routingCode) > 35)) {
            throw new \InvalidArgumentException('invalid length for $routingCode when calling ResponseItem., must be smaller than or equal to 35.');
        }
        if ((mb_strlen($routingCode) < 0)) {
            throw new \InvalidArgumentException('invalid length for $routingCode when calling ResponseItem., must be bigger than or equal to 0.');
        }

        $this->container['routingCode'] = $routingCode;

        return $this;
    }

    /**
     * Gets returnShipmentNo
     *
     * @return string|null
     */
    public function getReturnShipmentNo()
    {
        return $this->container['returnShipmentNo'];
    }

    /**
     * Sets returnShipmentNo
     *
     * @param string|null $returnShipmentNo returnShipmentNo
     *
     * @return self
     */
    public function setReturnShipmentNo($returnShipmentNo)
    {
        if (is_null($returnShipmentNo)) {
            throw new \InvalidArgumentException('non-nullable returnShipmentNo cannot be null');
        }
        if ((mb_strlen($returnShipmentNo) > 50)) {
            throw new \InvalidArgumentException('invalid length for $returnShipmentNo when calling ResponseItem., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($returnShipmentNo) < 0)) {
            throw new \InvalidArgumentException('invalid length for $returnShipmentNo when calling ResponseItem., must be bigger than or equal to 0.');
        }

        $this->container['returnShipmentNo'] = $returnShipmentNo;

        return $this;
    }

    /**
     * Gets sstatus
     *
     * @return \OpenAPI\Client\Dhl\Model\RequestStatus
     */
    public function getSstatus()
    {
        return $this->container['sstatus'];
    }

    /**
     * Sets sstatus
     *
     * @param \OpenAPI\Client\Dhl\Model\RequestStatus $sstatus sstatus
     *
     * @return self
     */
    public function setSstatus($sstatus)
    {
        if (is_null($sstatus)) {
            throw new \InvalidArgumentException('non-nullable sstatus cannot be null');
        }
        $this->container['sstatus'] = $sstatus;

        return $this;
    }

    /**
     * Gets shipmentRefNo
     *
     * @return string|null
     */
    public function getShipmentRefNo()
    {
        return $this->container['shipmentRefNo'];
    }

    /**
     * Sets shipmentRefNo
     *
     * @param string|null $shipmentRefNo shipmentRefNo
     *
     * @return self
     */
    public function setShipmentRefNo($shipmentRefNo)
    {
        if (is_null($shipmentRefNo)) {
            throw new \InvalidArgumentException('non-nullable shipmentRefNo cannot be null');
        }
        if ((mb_strlen($shipmentRefNo) > 50)) {
            throw new \InvalidArgumentException('invalid length for $shipmentRefNo when calling ResponseItem., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($shipmentRefNo) < 6)) {
            throw new \InvalidArgumentException('invalid length for $shipmentRefNo when calling ResponseItem., must be bigger than or equal to 6.');
        }

        $this->container['shipmentRefNo'] = $shipmentRefNo;

        return $this;
    }

    /**
     * Gets label
     *
     * @return \OpenAPI\Client\Dhl\Model\Document|null
     */
    public function getLabel()
    {
        return $this->container['label'];
    }

    /**
     * Sets label
     *
     * @param \OpenAPI\Client\Dhl\Model\Document|null $label label
     *
     * @return self
     */
    public function setLabel($label)
    {
        if (is_null($label)) {
            throw new \InvalidArgumentException('non-nullable label cannot be null');
        }
        $this->container['label'] = $label;

        return $this;
    }

    /**
     * Gets returnLabel
     *
     * @return \OpenAPI\Client\Dhl\Model\Document|null
     */
    public function getReturnLabel()
    {
        return $this->container['returnLabel'];
    }

    /**
     * Sets returnLabel
     *
     * @param \OpenAPI\Client\Dhl\Model\Document|null $returnLabel returnLabel
     *
     * @return self
     */
    public function setReturnLabel($returnLabel)
    {
        if (is_null($returnLabel)) {
            throw new \InvalidArgumentException('non-nullable returnLabel cannot be null');
        }
        $this->container['returnLabel'] = $returnLabel;

        return $this;
    }

    /**
     * Gets customsDoc
     *
     * @return \OpenAPI\Client\Dhl\Model\Document|null
     */
    public function getCustomsDoc()
    {
        return $this->container['customsDoc'];
    }

    /**
     * Sets customsDoc
     *
     * @param \OpenAPI\Client\Dhl\Model\Document|null $customsDoc customsDoc
     *
     * @return self
     */
    public function setCustomsDoc($customsDoc)
    {
        if (is_null($customsDoc)) {
            throw new \InvalidArgumentException('non-nullable customsDoc cannot be null');
        }
        $this->container['customsDoc'] = $customsDoc;

        return $this;
    }

    /**
     * Gets codLabel
     *
     * @return \OpenAPI\Client\Dhl\Model\Document|null
     */
    public function getCodLabel()
    {
        return $this->container['codLabel'];
    }

    /**
     * Sets codLabel
     *
     * @param \OpenAPI\Client\Dhl\Model\Document|null $codLabel codLabel
     *
     * @return self
     */
    public function setCodLabel($codLabel)
    {
        if (is_null($codLabel)) {
            throw new \InvalidArgumentException('non-nullable codLabel cannot be null');
        }
        $this->container['codLabel'] = $codLabel;

        return $this;
    }

    /**
     * Gets validationMessages
     *
     * @return \OpenAPI\Client\Dhl\Model\ValidationMessageItem[]|null
     */
    public function getValidationMessages()
    {
        return $this->container['validationMessages'];
    }

    /**
     * Sets validationMessages
     *
     * @param \OpenAPI\Client\Dhl\Model\ValidationMessageItem[]|null $validationMessages Optional validation messages attached to the shipment.
     *
     * @return self
     */
    public function setValidationMessages($validationMessages)
    {
        if (is_null($validationMessages)) {
            throw new \InvalidArgumentException('non-nullable validationMessages cannot be null');
        }
        $this->container['validationMessages'] = $validationMessages;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


